//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTGTest.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_Sites
    {
        public int UserSiteId { get; set; }
        public int SiteId { get; set; }
        public string UserId { get; set; }
        public System.DateTime LastLogin { get; set; }
        public System.DateTime LastUpdate { get; set; }
        public bool BuyingInfluence { get; set; }
        public bool ConsumerBuyingInfluence { get; set; }
    }
}
